FROM pkjmesra/fastquant_debian_gnu_linux:latest as fastquant-ready
ENV PYTHONUNBUFFERED 1
ENV PYTHON_TA_LIB_VERSION 0.4.19

# TA-Lib
RUN wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz && \
  tar -xvzf ta-lib-0.4.0-src.tar.gz && \
  cd ta-lib/ && \
  ./configure --prefix=/usr && \
  make && \
  make install

RUN rm -rf ta-lib ta-lib-0.4.0-src.tar.gz
RUN pip3 install ta-lib==${PYTHON_TA_LIB_VERSION}

CMD ["python3"]

RUN python3 -c 'import numpy, talib; close = numpy.random.random(100); output = talib.SMA(close); print(output)'

RUN python3 -c 'from fastquant import backtest, get_yahoo_data; data = get_yahoo_data("TSLA", "2020-11-01", "2021-01-30");backtest("smac", data, fast_period=15, slow_period=20, verbose=False, plot=False)'
